import { LeitnerCard } from '@/types/leitner';

export const INITIAL_SAMPLE_LEITNER_CARDS: LeitnerCard[] = [
  {
    id: 'sample-card-ace-bradykinin',
    userId: 'guest-system',
    module: 4,
    moduleName: { fa: 'ماژول ۴: دانش بالینی داروسازی استرالیا', en: 'Module 4: Clinical Knowledge' },
    category: 'سیستم قلب و عروق (Cardiovascular)',
    topic: 'مهارکننده‌های رنین-آنژیوتانسین (RAAS Inhibitors)',
    question: {
      fa: 'مکانیسم اصلی سرفه خشک ناشی از انالاپریل یا رامیپریل چیست و در صورت عدم تحمل بیمار، خط اول جایگزینی در دستورالعمل‌های بالینی استرالیا چیست؟',
      en: 'What is the primary mechanism of dry cough induced by Enalapril/Ramipril, and what is the first-line guideline replacement in Australia?',
    },
    answer: {
      fa: 'سرفه خشک به دلیل مهار آنزیم ACE و در نتیجه تجمع برادی‌کینین (Bradykinin) و ماده P در ریه‌ها رخ می‌دهد (در ۱۰ تا ۲۰٪ بیماران). در صورت بروز، بیمار باید به یک مسدودکننده گیرنده آنژیوتانسین ۲ (ARB) مانند تلمیسارتان یا کاندسارتان سوئیچ شود زیرا ARBها بر متابولیسم برادی‌کینین اثری ندارند.',
      en: 'The dry cough is caused by ACE inhibition leading to the accumulation of bradykinin and substance P in the respiratory tract (10-20% incidence). The first-line Australian guideline recommendation is switching to an Angiotensin II Receptor Blocker (ARB) such as Telmisartan or Candesartan, which do not impair bradykinin breakdown.',
    },
    pearl: {
      fa: 'نکته طلایی امتحانی: شروع ARB بلافاصله پس از قطع ACEi مجاز است و نیازی به دوره شستشو (Washout) نیست، برعکس تعویض با ساکوبیتریل/والسارتان (Entresto) که حتماً نیاز به ۳۶ ساعت Washout جهت پیشگیری از آنژیوادم شدید دارد.',
      en: 'High-Yield Exam Pearl: Switching from ACEi to ARB requires no washout period. However, switching from ACEi to Sacubitril/Valsartan (ARNI) strictly mandates a 36-hour washout to prevent life-threatening angioedema.',
    },
    type: 'clinical_pearl',
    box: 1,
    nextReviewDate: new Date().toISOString(),
    reviewCount: 0,
    successCount: 0,
    tags: ['Cardiology', 'RAAS', 'ACE-Inhibitors', 'Bradykinin', 'ARNI-Washout', 'AMH-Guideline'],
    knowledgeTree: {
      domain: { fa: 'داروسازی بالینی استرالیا', en: 'Australian Clinical Pharmacy' },
      system: { fa: 'سیستم قلب و عروق و کلیه', en: 'Cardiovascular & Renal System' },
      subsystem: { fa: 'داروهای فشار خون و نارسایی قلبی', en: 'Antihypertensives & Heart Failure' },
      condition: { fa: 'داروهای فشار خون و نارسایی قلبی', en: 'Antihypertensives & Heart Failure' },
      subClass: { fa: 'مهارکننده‌های رنین-آنژیوتانسین (ACEi vs ARB)', en: 'RAAS Inhibitors (ACEi vs ARB)' },
      drugGroup: { fa: 'مهارکننده‌های رنین-آنژیوتانسین (ACEi vs ARB)', en: 'RAAS Inhibitors (ACEi vs ARB)' },
      microTopic: { fa: 'عوارض برادی‌کینین، سرفه خشک و سوئیچ به ARB', en: 'Bradykinin Accumulation, Dry Cough & ARB Switch' },
      clinicalAspect: { fa: 'عوارض برادی‌کینین، سرفه خشک و سوئیچ به ARB', en: 'Bradykinin Accumulation, Dry Cough & ARB Switch' },
      path: {
        fa: ['داروسازی بالینی استرالیا', 'سیستم قلب و عروق و کلیه', 'داروهای فشار خون و نارسایی قلبی', 'مهارکننده‌های رنین-آنژیوتانسین (ACEi vs ARB)', 'عوارض برادی‌کینین، سرفه خشک و سوئیچ به ARB'],
        en: ['Australian Clinical Pharmacy', 'Cardiovascular & Renal System', 'Antihypertensives & Heart Failure', 'RAAS Inhibitors (ACEi vs ARB)', 'Bradykinin Accumulation, Dry Cough & ARB Switch'],
      },
    },
    sourceSnippet: 'Australian Medicines Handbook (AMH) & Therapeutic Guidelines (eTG): ACE inhibitors block kininase II leading to bradykinin accumulation. Dry cough resolves within 1-4 weeks of cessation. Switch to ARB.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sample-card-asthma-smart',
    userId: 'guest-system',
    module: 4,
    moduleName: { fa: 'ماژول ۴: دانش بالینی داروسازی استرالیا', en: 'Module 4: Clinical Knowledge' },
    category: 'سیستم تنفسی (Respiratory)',
    topic: 'مدیریت آسم بزرگسالان (Asthma Guidelines)',
    question: {
      fa: 'بر اساس گایدلاین ملی آسم استرالیا (National Asthma Council Australia)، درمان نگهدارنده و تسکین‌دهنده ترجیحی (SMART / AIR) برای نوجوانان و بزرگسالان مبتلا به آسم متوسط تا شدید چیست؟',
      en: 'According to the National Asthma Council Australia guidelines, what is the preferred SMART/AIR regimen for adolescents and adults with moderate to severe asthma?',
    },
    answer: {
      fa: 'استفاده از ترکیب کورتیکواستروئید استنشاقی با فورموترول (بکلومتاسون/فورموترول یا بودزوناید/فورموترول مانند Symbicort Rapihaler/Turbuhaler) هم به عنوان داروی نگهدارنده روزانه و هم به عنوان تسکین‌دهنده (Reliever) در هنگام بروز علائم.',
      en: 'Low/medium dose Inhaled Corticosteroid (ICS) combined with fast- and long-acting beta2-agonist Formoterol (e.g., Budesonide/Formoterol Turbuhaler/Rapihaler or Beclometasone/Formoterol) taken as daily maintenance AND as needed for symptom relief (SMART / AIR approach).',
    },
    pearl: {
      fa: 'نکته کلیدی: سالمترول (Salmeterol) به دلیل شروع اثر آهسته‌تر نسبت به فورموترول (Formoterol) به هیچ وجه نباید به عنوان داروی تسکین‌دهنده (Reliever) استفاده شود. برچسب CAL الزامی: شستشوی دهان پس از مصرف برای پیشگیری از کاندیدیازیس دهانی.',
      en: 'Key Clinical Pitfall: Salmeterol CANNOT be used for SMART because of its delayed onset of action (10-20 min vs 1-3 min for Formoterol). Mandatory CAL label: Rinse mouth after inhalation to prevent oral candidiasis and hoarseness.',
    },
    type: 'clinical_pearl',
    box: 1,
    nextReviewDate: new Date().toISOString(),
    reviewCount: 0,
    successCount: 0,
    tags: ['Respiratory', 'Asthma', 'NAC-Guidelines', 'SMART-AIR', 'Symbicort', 'Formoterol', 'CAL-Label'],
    knowledgeTree: {
      domain: { fa: 'داروسازی بالینی استرالیا', en: 'Australian Clinical Pharmacy' },
      system: { fa: 'سیستم تنفسی و آلرژی', en: 'Respiratory & Allergic System' },
      subsystem: { fa: 'بیماری‌های انسدادی ریه (آسم و COPD)', en: 'Obstructive Airway Diseases (Asthma & COPD)' },
      condition: { fa: 'بیماری‌های انسدادی ریه (آسم و COPD)', en: 'Obstructive Airway Diseases (Asthma & COPD)' },
      subClass: { fa: 'ترکیبات ICS + LABA سریع‌الاثر (Budesonide/Formoterol)', en: 'ICS + Fast-Acting LABA (Budesonide/Formoterol)' },
      drugGroup: { fa: 'ترکیبات ICS + LABA سریع‌الاثر (Budesonide/Formoterol)', en: 'ICS + Fast-Acting LABA (Budesonide/Formoterol)' },
      microTopic: { fa: 'پروتکل SMART/AIR و برچسب‌های احتیاط شستشوی دهان', en: 'SMART/AIR Regimen & Oral Rinsing CAL Requirements' },
      clinicalAspect: { fa: 'پروتکل SMART/AIR و برچسب‌های احتیاط شستشوی دهان', en: 'SMART/AIR Regimen & Oral Rinsing CAL Requirements' },
      path: {
        fa: ['داروسازی بالینی استرالیا', 'سیستم تنفسی و آلرژی', 'بیماری‌های انسدادی ریه (آسم و COPD)', 'ترکیبات ICS + LABA سریع‌الاثر (Budesonide/Formoterol)', 'پروتکل SMART/AIR و برچسب‌های احتیاط شستشوی دهان'],
        en: ['Australian Clinical Pharmacy', 'Respiratory & Allergic System', 'Obstructive Airway Diseases (Asthma & COPD)', 'ICS + Fast-Acting LABA (Budesonide/Formoterol)', 'SMART/AIR Regimen & Oral Rinsing CAL Requirements'],
      },
    },
    sourceSnippet: 'National Asthma Council Australia (NAC) Asthma Handbook 2024: Single Inhaler Maintenance and Reliever Therapy (SMART) with Budesonide/Formoterol is the preferred anti-inflammatory reliever regimen.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sample-card-s3-pseudoephedrine',
    userId: 'guest-system',
    module: 2,
    moduleName: { fa: 'ماژول ۲: انتخاب محصول و جدول‌بندی SUSMP', en: 'Module 2: Scheduling & SUSMP' },
    category: 'قوانین و جدول‌بندی داروها (SUSMP Scheduling)',
    topic: 'داروهای داروساز (Schedule 3 Pharmacist Only)',
    question: {
      fa: 'در استرالیا، تحویل سودوافدرین خوراکی (S3 Pharmacist Only) مستلزم چه شروط قانونی، ثبت هویت و موارد منع مصرف بالینی است؟',
      en: 'In Australia, what are the legal supply requirements, mandatory ID recording (Project STOP), and contraindications for oral Pseudoephedrine (Schedule 3)?',
    },
    answer: {
      fa: '۱. مشاوره مستقیم و حضوری داروساز با بیمار الزامی است. ۲. احراز هویت با مدرک عکس‌دار دولتی (گواهینامه یا پاسپورت) و ثبت در سامانه آنلاین Project STOP جهت پیشگیری از سوءمصرف. ۳. موارد منع مصرف: فشار خون بالای کنترل‌نشده، بیماری عروق کرونر شدید، گلوکوم زاویه بسته و مصرف همزمان یا تا ۱۴ روز گذشته مهارکننده‌های MAO.',
      en: '1. Mandatory direct pharmacist-patient therapeutic consultation. 2. Verification of government photo ID (driver licence/passport) and real-time electronic recording in Project STOP. 3. Major contraindications: Uncontrolled severe hypertension, severe coronary artery disease, closed-angle glaucoma, and concurrent or within 14 days of MAO inhibitors.',
    },
    pearl: {
      fa: 'تله قانونی: طبق SUSMP استرالیا، قرص‌های ترکیبی پسودوافدرین با آنتی‌هیستامین یا مسکن در بسته‌های تا ۷۲۰ میلی‌گرم تحت S3 و بسته‌های بزرگتر S4 (نیاز به نسخه پزشک) هستند.',
      en: 'Legal Pitfall: In SUSMP, oral pseudoephedrine formulations with pack sizes containing up to 720 mg total pseudoephedrine are Schedule 3; exceeding quantities become Schedule 4 Prescription Only.',
    },
    type: 'scheduling_legal',
    box: 1,
    nextReviewDate: new Date().toISOString(),
    reviewCount: 0,
    successCount: 0,
    tags: ['Pharmacy-Law', 'SUSMP', 'Schedule-3', 'Pseudoephedrine', 'Project-STOP', 'Hypertension-Warning'],
    knowledgeTree: {
      domain: { fa: 'قوانین و نسخه استرالیا', en: 'Australian Pharmacy Law & Dispensing' },
      system: { fa: 'جدول‌بندی سموم و داروها (SUSMP)', en: 'Poisons Standard & Scheduling (SUSMP)' },
      subsystem: { fa: 'داروهای فقط با نظر داروساز (Schedule 3)', en: 'Pharmacist Only Medicines (Schedule 3)' },
      condition: { fa: 'داروهای فقط با نظر داروساز (Schedule 3)', en: 'Pharmacist Only Medicines (Schedule 3)' },
      subClass: { fa: 'ضداحتقان‌های سمپاتومیمتیک خوراکی (Pseudoephedrine)', en: 'Oral Sympathomimetic Decongestants (Pseudoephedrine)' },
      drugGroup: { fa: 'ضداحتقان‌های سمپاتومیمتیک خوراکی (Pseudoephedrine)', en: 'Oral Sympathomimetic Decongestants (Pseudoephedrine)' },
      microTopic: { fa: 'سامانه Project STOP، احراز هویت و موارد منع در فشار خون', en: 'Project STOP Mandatory Logging & Cardiovascular Contraindications' },
      clinicalAspect: { fa: 'سامانه Project STOP، احراز هویت و موارد منع در فشار خون', en: 'Project STOP Mandatory Logging & Cardiovascular Contraindications' },
      path: {
        fa: ['قوانین و نسخه استرالیا', 'جدول‌بندی سموم و داروها (SUSMP)', 'داروهای فقط با نظر داروساز (Schedule 3)', 'ضداحتقان‌های سمپاتومیمتیک خوراکی (Pseudoephedrine)', 'سامانه Project STOP، احراز هویت و موارد منع در فشار خون'],
        en: ['Australian Pharmacy Law & Dispensing', 'Poisons Standard & Scheduling (SUSMP)', 'Pharmacist Only Medicines (Schedule 3)', 'Oral Sympathomimetic Decongestants (Pseudoephedrine)', 'Project STOP Mandatory Logging & Cardiovascular Contraindications'],
      },
    },
    sourceSnippet: 'Standard for the Uniform Scheduling of Medicines and Poisons (SUSMP) & Pharmacy Board of Australia Guidelines on Pharmacist-Only Medicines: Pseudoephedrine S3 recording in Project STOP.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sample-card-triage-cough-redflags',
    userId: 'guest-system',
    module: 1,
    moduleName: { fa: 'ماژول ۱: تریاژ و شرح حال بیمار (OTC Roleplay)', en: 'Module 1: OTC Triage & Consultation' },
    category: 'تریاژ و علائم هشدار دهنده (Red Flags)',
    topic: 'تریاژ بالینی سرفه و ارجاع فوری (Cough Red Flags)',
    question: {
      fa: 'در پروتکل تریاژ داروساز (WHAT-STOP-GO)، چه علائم خطری (Red Flags) در بیمار مراجعه‌کننده با سرفه نیازمند ارجاع فوری پزشکی (Urgent GP Referral) است و نباید فرآورده OTC داده شود؟',
      en: 'Under the WHAT-STOP-GO triage protocol, what clinical Red Flags in a coughing patient mandate immediate Medical/GP referral instead of OTC cough suppressants?',
    },
    answer: {
      fa: '۱. سرفه مداوم بیش از ۳ تا ۴ هفته (مشکوک به برونکوژنیک یا سل). ۲. هموپتیزی (خلط خونی). ۳. تنگی نفس حاد (Stridor / Dyspnoea). ۴. درد قفسه سینه پلورتیک یا تب بالا و تعریق شبانه با کاهش وزن ناخواسته. ۵. مصرف همزمان داروهای مهارکننده ACE یا سابقه بیماری قلبی-تنفسی زمینه‌ای کنترل‌نشده.',
      en: '1. Chronic cough persisting > 3-4 weeks (rule out malignancy or chronic pathology). 2. Haemoptysis (blood in sputum). 3. Stridor, wheezing, or acute breathlessness. 4. Pleuritic chest pain, high persistent fever, drenching night sweats, or unexplained weight loss. 5. Suspicion of ACEi adverse reaction or underlying heart failure.',
    },
    pearl: {
      fa: 'هشدار مهم: فرآورده‌های ضد سرفه OTC حاوی کدئین یا دکسترومتورفان هرگز نباید برای سرکوب سرفه همراه با علائم هشدار تجویز شوند. در کودکان زیر ۶ سال مصرف ضدسرفه‌های دکونژستانت OTC به طور کامل در استرالیا ممنوع است.',
      en: 'Critical Safety Note: OTC cough suppressants must never be given to mask red flags. In Australia (TGA mandate), OTC cough and cold medicines containing antihistamines or decongestants are completely contraindicated in children under 6 years.',
    },
    type: 'triage_redflag',
    box: 1,
    nextReviewDate: new Date().toISOString(),
    reviewCount: 0,
    successCount: 0,
    tags: ['Triage', 'OTC-Consultation', 'Cough-Red-Flags', 'Haemoptysis', 'WHAT-STOP-GO', 'Pediatric-Contraindications'],
    knowledgeTree: {
      domain: { fa: 'تریاژ و نقش داروساز OTC', en: 'OTC Patient Triage & Roleplay' },
      system: { fa: 'پروتکل تریاژ علائم تنفسی', en: 'Respiratory Symptom Assessment Protocols' },
      subsystem: { fa: 'تریاژ سرفه حاد در برابر مزمن', en: 'Acute vs Chronic Cough Triage' },
      condition: { fa: 'تریاژ سرفه حاد در برابر مزمن', en: 'Acute vs Chronic Cough Triage' },
      subClass: { fa: 'پروتکل ارزیابی WHAT-STOP-GO', en: 'WHAT-STOP-GO Clinical Framework' },
      drugGroup: { fa: 'پروتکل ارزیابی WHAT-STOP-GO', en: 'WHAT-STOP-GO Clinical Framework' },
      microTopic: { fa: 'هموپتیزی، سرفه بیش از ۳ هفته و منع مصرف اطفال زیر ۶ سال', en: 'Haemoptysis, Chronic Duration & Under 6 Contraindications' },
      clinicalAspect: { fa: 'هموپتیزی، سرفه بیش از ۳ هفته و منع مصرف اطفال زیر ۶ سال', en: 'Haemoptysis, Chronic Duration & Under 6 Contraindications' },
      path: {
        fa: ['تریاژ و نقش داروساز OTC', 'پروتکل تریاژ علائم تنفسی', 'تریاژ سرفه حاد در برابر مزمن', 'پروتکل ارزیابی WHAT-STOP-GO', 'هموپتیزی، سرفه بیش از ۳ هفته و منع مصرف اطفال زیر ۶ سال'],
        en: ['OTC Patient Triage & Roleplay', 'Respiratory Symptom Assessment Protocols', 'Acute vs Chronic Cough Triage', 'WHAT-STOP-GO Clinical Framework', 'Haemoptysis, Chronic Duration & Under 6 Contraindications'],
      },
    },
    sourceSnippet: 'PSA Primary Care Guidelines: Cough management in community pharmacy. Red flags including haemoptysis, dyspnoea, and cough lasting longer than 3 weeks require medical referral.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sample-card-sglt2-euglycemic-dka',
    userId: 'guest-system',
    module: 4,
    moduleName: { fa: 'ماژول ۴: دانش بالینی داروسازی استرالیا', en: 'Module 4: Clinical Knowledge' },
    category: 'سیستم غدد و متابولیسم (Endocrinology)',
    topic: 'داروهای ضد دیابت مهارکننده SGLT2 (SGLT2 Inhibitors)',
    question: {
      fa: 'داروساز در زمان تحویل امپاگلیفلوزین (Jardiance) یا داپاگلیفلوزین (Forxiga) باید در مورد کدام عارضه نادر ولی کشنده (euglycaemic DKA) و پروتکل قطع قبل از جراحی مشاوره دهد؟',
      en: 'When dispensing Empagliflozin (Jardiance) or Dapagliflozin (Forxiga), what counseling regarding euglycaemic DKA and perioperative cessation rules must be provided?',
    },
    answer: {
      fa: '۱. کتواسیدوز دیابتی با گلوکز نرمال (euglycaemic DKA): ممکن است با قند خون کمتر از ۱۴ mmol/L رخ دهد؛ علائم شامل تهوع، درد شکم، تنگی نفس و خستگی شدید است. ۲. قانون قطع قبل از جراحی (SADMANS rule): دارو باید حداقل ۳ روز (و در صورت جراحی‌های روده یا مصرف بسیار کم کربوهیدرات/ناشتایی طولانی ۳ روز کامل) قبل از عمل‌های جراحی الکتیو یا بیماری‌های حاد تب‌دار قطع شود.',
      en: '1. Euglycaemic Diabetic Ketoacidosis (euDKA): DKA can develop with normal or only moderately elevated blood glucose (<14 mmol/L); warning signs include malaise, nausea, abdominal pain, and dyspnoea. 2. Perioperative cessation rule: SGLT2 inhibitors must be ceased at least 3 days prior to major surgery or acute dehydrating illnesses (Sick Day Rules / SADMANS).',
    },
    pearl: {
      fa: 'نکته نسخه و ایمنی: عفونت‌های قارچی تناسلی (Genital Mycotic Infections) شایع‌ترین عارضه موضعی است؛ توصیه به بهداشت فردی و مصرف کافی مایعات جهت پیشگیری از افت فشار خون وضعیتی و دهیدراسیون ضروری است.',
      en: 'Safety Pearl: Genital mycotic candidiasis is the most frequent adverse effect. Advise adequate fluid intake to avoid volume depletion, orthostatic hypotension, and monitor renal function (eGFR threshold on PBS).',
    },
    type: 'cal_warning',
    box: 1,
    nextReviewDate: new Date().toISOString(),
    reviewCount: 0,
    successCount: 0,
    tags: ['Endocrinology', 'Diabetes', 'SGLT2i', 'Empagliflozin', 'euDKA', 'Perioperative-Cessation', 'SADMANS'],
    knowledgeTree: {
      domain: { fa: 'داروسازی بالینی استرالیا', en: 'Australian Clinical Pharmacy' },
      system: { fa: 'سیستم غدد، دیابت و متابولیسم', en: 'Endocrine & Metabolic System' },
      subsystem: { fa: 'داروهای ضد دیابت نوع ۲ و بیماری‌های مزمن کلیه', en: 'Type 2 Diabetes & Chronic Kidney Disease' },
      condition: { fa: 'داروهای ضد دیابت نوع ۲ و بیماری‌های مزمن کلیه', en: 'Type 2 Diabetes & Chronic Kidney Disease' },
      subClass: { fa: 'مهارکننده‌های SGLT2 کلیوی (Gliflozins)', en: 'Sodium-Glucose Cotransporter-2 (SGLT2) Inhibitors' },
      drugGroup: { fa: 'مهارکننده‌های SGLT2 کلیوی (Gliflozins)', en: 'Sodium-Glucose Cotransporter-2 (SGLT2) Inhibitors' },
      microTopic: { fa: 'کتواسیدوز یوگلایسمیک (euDKA) و قطع ۳ روز قبل جراحی', en: 'Euglycaemic DKA & 3-Day Perioperative Sick-Day Cessation' },
      clinicalAspect: { fa: 'کتواسیدوز یوگلایسمیک (euDKA) و قطع ۳ روز قبل جراحی', en: 'Euglycaemic DKA & 3-Day Perioperative Sick-Day Cessation' },
      path: {
        fa: ['داروسازی بالینی استرالیا', 'سیستم غدد، دیابت و متابولیسم', 'داروهای ضد دیابت نوع ۲ و بیماری‌های مزمن کلیه', 'مهارکننده‌های SGLT2 کلیوی (Gliflozins)', 'کتواسیدوز یوگلایسمیک (euDKA) و قطع ۳ روز قبل جراحی'],
        en: ['Australian Clinical Pharmacy', 'Endocrine & Metabolic System', 'Type 2 Diabetes & Chronic Kidney Disease', 'Sodium-Glucose Cotransporter-2 (SGLT2) Inhibitors', 'Euglycaemic DKA & 3-Day Perioperative Sick-Day Cessation'],
      },
    },
    sourceSnippet: 'Australian Diabetes Society (ADS) Perioperative Guidelines: SGLT2 inhibitors must be ceased 3 days (approx 72 hours) prior to elective surgery to mitigate euDKA risks.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sample-card-s8-safe-custody',
    userId: 'guest-system',
    module: 2,
    moduleName: { fa: 'ماژول ۲: انتخاب محصول و قوانین استرالیا', en: 'Module 2: Scheduling & Law' },
    category: 'قوانین داروهای تحت کنترل (Schedule 8 Controlled Drugs)',
    topic: 'نگهداری در گاوصندوق، ثبت و سقف اعتبار نسخه S8',
    question: {
      fa: 'الزامات قانونی نگهداری در گاوصندوق امنیتی (Safe Custody)، سقف اعتبار نسخه، و ثبت در دفتر S8 Register در داروخانه‌های استرالیا چیست؟',
      en: 'What are the Australian legal requirements for S8 Safe Custody, prescription validity periods (6 months), and S8 Register balance reconciliations?',
    },
    answer: {
      fa: '۱. نگهداری در گاوصندوق فولادی با ضخامت حداقل ۱۰ میلی‌متر و قفل کلیدی/ترکیبی مجهز به اتصال محکم به بتن کف یا دیوار. ۲. سقف اعتبار نسخه‌های Schedule 8 حداکثر ۶ ماه از تاریخ صدور است (در مقایسه با ۱۲ ماه برای داروهای Schedule 4 معمولی). ۳. هرگونه ورود، خروج، یا امحا باید بلافاصله با ذکر نام بیمار، پزشک، تاریخ، شماره نسخه و موجودی باقیمانده ثبت و به طور منظم (حداقل ماهانه یا دوهفته‌ای بر حسب ایالت) انبارگردانی شود.',
      en: '1. Must be stored in a dedicated steel safe (minimum 10mm steel plate construction) securely bolted to the concrete floor/wall. 2. S8 prescriptions have a strict maximum legal validity of 6 months from the date of prescribing (unlike S4 which is 12 months). 3. Every receipt, supply, and discard must be immediately documented in the Controlled Drugs Register with running balance reconciliation.',
    },
    pearl: {
      fa: 'تله امتحانی OPRA: در صورت وجود تکرار (Repeats) در نسخه S8، اصل نسخه و تمام فرم‌های تکرار باید در همان داروخانه‌ای که اولین بار تحویل داده شده نگهداری شوند (مگر با مجوز رسمی یا شرایط انتقال خاص ایالتی).',
      en: 'OPRA Exam Trap: S8 repeat authorizations must remain retained at the pharmacy where the initial dispensing took place (inter-pharmacy transfers strictly regulated by state poisons legislation).',
    },
    type: 'scheduling_legal',
    box: 1,
    nextReviewDate: new Date().toISOString(),
    reviewCount: 0,
    successCount: 0,
    tags: ['Pharmacy-Law', 'Schedule-8', 'Controlled-Drugs', 'Safe-Custody', '6-Month-Validity', 'S8-Register'],
    knowledgeTree: {
      domain: { fa: 'قوانین و نسخه استرالیا', en: 'Australian Pharmacy Law & Dispensing' },
      system: { fa: 'داروهای تحت کنترل ویژه (Schedule 8)', en: 'Controlled Drugs & Narcotics (Schedule 8)' },
      subsystem: { fa: 'الزامات نگهداری و اعتبار قانونی نسخه', en: 'Safe Custody & Legal Validity Standards' },
      condition: { fa: 'الزامات نگهداری و اعتبار قانونی نسخه', en: 'Safe Custody & Legal Validity Standards' },
      subClass: { fa: 'ضوابط گاوصندوق و انبارگردانی S8 Register', en: 'Safe Construction & Running Balance Reconciliation' },
      drugGroup: { fa: 'ضوابط گاوصندوق و انبارگردانی S8 Register', en: 'Safe Construction & Running Balance Reconciliation' },
      microTopic: { fa: 'اعتبار ۶ ماهه، نگهداری تکرارها در یک داروخانه و تلرانس موازنه', en: '6-Month Expiry, Repeat Retention & Balance Audits' },
      clinicalAspect: { fa: 'اعتبار ۶ ماهه، نگهداری تکرارها در یک داروخانه و تلرانس موازنه', en: '6-Month Expiry, Repeat Retention & Balance Audits' },
      path: {
        fa: ['قوانین و نسخه استرالیا', 'داروهای تحت کنترل ویژه (Schedule 8)', 'الزامات نگهداری و اعتبار قانونی نسخه', 'ضوابط گاوصندوق و انبارگردانی S8 Register', 'اعتبار ۶ ماهه، نگهداری تکرارها در یک داروخانه و تلرانس موازنه'],
        en: ['Australian Pharmacy Law & Dispensing', 'Controlled Drugs & Narcotics (Schedule 8)', 'Safe Custody & Legal Validity Standards', 'Safe Construction & Running Balance Reconciliation', '6-Month Expiry, Repeat Retention & Balance Audits'],
      },
    },
    sourceSnippet: 'State and Territory Poisons and Therapeutic Goods Regulations: Schedule 8 controlled drugs storage, register reconciliations, and maximum 6-month validity rules.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sample-card-fred-reg24-pbs',
    userId: 'guest-system',
    module: 3,
    moduleName: { fa: 'ماژول ۳: شبیه‌ساز نسخه پیچی فرد (Fred Dispense)', en: 'Module 3: Fred Dispense Simulator' },
    category: 'قوانین PBS و کلیدهای میانبر نرم‌افزار Fred',
    topic: 'تجویز کلیه تکرارها در یک نوبت (Regulation 24 / PBS Supply)',
    question: {
      fa: 'در نرم‌افزار Fred Dispense Plus، شروط قانونی و کلید میانبر تأمین همزمان اصل و تکرارهای نسخه (Regulation 24 / Rule 24) تحت بیمه دارویی PBS چیست؟',
      en: 'In Fred Dispense Plus, what are the legal PBS requirements and shortcut keys for simultaneous supply of original and repeats under Regulation 24?',
    },
    answer: {
      fa: '۱. شروط قانونی Reg 24: پزشک باید عبارت "Regulation 24" یا "Supply all repeats at once" را روی نسخه دست‌نویس یا الکترونیک تایید نماید؛ این امر زمانی مجاز است که بیمار در مناطق دورافتاده زندگی کند یا به دلیل شرایط حاد مسافرتی/دسترسی امکان مراجعه مجدد نداشته باشد. ۲. در فرد دیسپنس، داروساز با فشردن کلید "5R" تمام تکرارها را به طور همزمان با تأیید PBS Claim پردازش و برچسب‌های تجمعی را چاپ می‌کند.',
      en: '1. Legal Reg 24 Criteria: Prescriber must endorse the prescription with "Regulation 24" or "Supply all repeats at once" where maximum PBS quantities would be insufficient or the patient lives in a remote area with restricted pharmacy access. 2. In Fred Dispense, entering shortcut "5R" (or selecting Supply All Repeats) dispenses all quantities simultaneously while generating consecutive PBS claim serials.',
    },
    pearl: {
      fa: 'نکته نسخه پیچی استرالیا: داروساز هرگز نمی‌تواند بدون دستور صریح پزشک و تاییدیه رسمی، یک نسخه را به صورت Regulation 24 تحویل دهد و تخطی از آن موجب عدم پرداخت (Rejection) بیمه Medicare و مسئولیت انضباطی است.',
      en: 'Dispensing Pearl: Pharmacists cannot invoke Regulation 24 at patient request without prescriber endorsement. Supplying without legal endorsement risks full PBS claim recovery and auditing penalties.',
    },
    type: 'scheduling_legal',
    box: 1,
    nextReviewDate: new Date().toISOString(),
    reviewCount: 0,
    successCount: 0,
    tags: ['Fred-Dispense', 'PBS', 'Regulation-24', 'Simultaneous-Supply', 'Dispensing-Shortcuts', '5R-Shortcut'],
    knowledgeTree: {
      domain: { fa: 'نسخه‌پیچی و قوانین دارویی استرالیا', en: 'Australian Dispensing & PBS Systems' },
      system: { fa: 'سیستم‌های نرم‌افزاری داروخانه (Fred Dispense Plus)', en: 'Pharmacy Dispensing Software (Fred Dispense)' },
      subsystem: { fa: 'فرآیندهای بیمه PBS و کلیدهای میانبر تحویل', en: 'PBS Claiming Protocols & Dispensing Shortcuts' },
      condition: { fa: 'فرآیندهای بیمه PBS و کلیدهای میانبر تحویل', en: 'PBS Claiming Protocols & Dispensing Shortcuts' },
      subClass: { fa: 'تجویز فوری تکرارها (Regulation 24 / Simultaneous Supply)', en: 'Simultaneous Supply & Regulation 24 Rules' },
      drugGroup: { fa: 'تجویز فوری تکرارها (Regulation 24 / Simultaneous Supply)', en: 'Simultaneous Supply & Regulation 24 Rules' },
      microTopic: { fa: 'کلید میانبر 5R در Fred، شرایط مسافت دوردست و استعلام مدیکر', en: 'Shortcut 5R in Fred, Remote Hardship & Medicare Claim Compliance' },
      clinicalAspect: { fa: 'کلید میانبر 5R در Fred، شرایط مسافت دوردست و استعلام مدیکر', en: 'Shortcut 5R in Fred, Remote Hardship & Medicare Claim Compliance' },
      path: {
        fa: ['نسخه‌پیچی و قوانین دارویی استرالیا', 'سیستم‌های نرم‌افزار داروخانه (Fred Dispense Plus)', 'فرآیندهای بیمه PBS و کلیدهای میانبر تحویل', 'تجویز فوری تکرارها (Regulation 24 / Simultaneous Supply)', 'کلید میانبر 5R در Fred، شرایط مسافت دوردست و استعلام مدیکر'],
        en: ['Australian Dispensing & PBS Systems', 'Pharmacy Dispensing Software (Fred Dispense)', 'PBS Claiming Protocols & Dispensing Shortcuts', 'Simultaneous Supply & Regulation 24 Rules', 'Shortcut 5R in Fred, Remote Hardship & Medicare Claim Compliance'],
      },
    },
    sourceSnippet: 'National Health (Pharmaceutical Benefits) Regulations: Regulation 24 allows simultaneous supply of PBS quantities and repeats upon medical practitioner endorsement.',
    createdAt: new Date().toISOString(),
  },
];
